<?php
/**
 * PfsAccountInitialDataUserdefined
 *
 * PHP version 5
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api mgmt.intaxx
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace AndyDune\MgmtIntaxxApi\Model;

use \ArrayAccess;
use \AndyDune\MgmtIntaxxApi\ObjectSerializer;

/**
 * PfsAccountInitialDataUserdefined Class Doc Comment
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PfsAccountInitialDataUserdefined implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PfsAccount_initialData_userdefined';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'occupation' => 'string',
'occupationProfession' => 'string',
'cardPurpose' => 'string',
'monthlyIncome' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'occupation' => null,
'occupationProfession' => null,
'cardPurpose' => null,
'monthlyIncome' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'occupation' => 'Occupation',
'occupationProfession' => 'Occupation_Profession',
'cardPurpose' => 'Card_Purpose',
'monthlyIncome' => 'Monthly_Income'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'occupation' => 'setOccupation',
'occupationProfession' => 'setOccupationProfession',
'cardPurpose' => 'setCardPurpose',
'monthlyIncome' => 'setMonthlyIncome'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'occupation' => 'getOccupation',
'occupationProfession' => 'getOccupationProfession',
'cardPurpose' => 'getCardPurpose',
'monthlyIncome' => 'getMonthlyIncome'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['occupation'] = isset($data['occupation']) ? $data['occupation'] : null;
        $this->container['occupationProfession'] = isset($data['occupationProfession']) ? $data['occupationProfession'] : null;
        $this->container['cardPurpose'] = isset($data['cardPurpose']) ? $data['cardPurpose'] : null;
        $this->container['monthlyIncome'] = isset($data['monthlyIncome']) ? $data['monthlyIncome'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets occupation
     *
     * @return string
     */
    public function getOccupation()
    {
        return $this->container['occupation'];
    }

    /**
     * Sets occupation
     *
     * @param string $occupation occupation
     *
     * @return $this
     */
    public function setOccupation($occupation)
    {
        $this->container['occupation'] = $occupation;

        return $this;
    }

    /**
     * Gets occupationProfession
     *
     * @return string
     */
    public function getOccupationProfession()
    {
        return $this->container['occupationProfession'];
    }

    /**
     * Sets occupationProfession
     *
     * @param string $occupationProfession occupationProfession
     *
     * @return $this
     */
    public function setOccupationProfession($occupationProfession)
    {
        $this->container['occupationProfession'] = $occupationProfession;

        return $this;
    }

    /**
     * Gets cardPurpose
     *
     * @return string
     */
    public function getCardPurpose()
    {
        return $this->container['cardPurpose'];
    }

    /**
     * Sets cardPurpose
     *
     * @param string $cardPurpose cardPurpose
     *
     * @return $this
     */
    public function setCardPurpose($cardPurpose)
    {
        $this->container['cardPurpose'] = $cardPurpose;

        return $this;
    }

    /**
     * Gets monthlyIncome
     *
     * @return string
     */
    public function getMonthlyIncome()
    {
        return $this->container['monthlyIncome'];
    }

    /**
     * Sets monthlyIncome
     *
     * @param string $monthlyIncome monthlyIncome
     *
     * @return $this
     */
    public function setMonthlyIncome($monthlyIncome)
    {
        $this->container['monthlyIncome'] = $monthlyIncome;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
