<?php
/**
 * CreditRequestInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api mgmt.intaxx
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AndyDune\MgmtIntaxxApi;

/**
 * CreditRequestInfoTest Class Doc Comment
 *
 * @category    Class
 * @description CreditRequestInfo
 * @package     AndyDune\MgmtIntaxxApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreditRequestInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreditRequestInfo"
     */
    public function testCreditRequestInfo()
    {
    }

    /**
     * Test attribute "desiredAmount"
     */
    public function testPropertyDesiredAmount()
    {
    }

    /**
     * Test attribute "landlinePhoneNumber"
     */
    public function testPropertyLandlinePhoneNumber()
    {
    }

    /**
     * Test attribute "mobilePhone"
     */
    public function testPropertyMobilePhone()
    {
    }

    /**
     * Test attribute "jobStatus"
     */
    public function testPropertyJobStatus()
    {
    }

    /**
     * Test attribute "netIncomePerMonth"
     */
    public function testPropertyNetIncomePerMonth()
    {
    }

    /**
     * Test attribute "nationality"
     */
    public function testPropertyNationality()
    {
    }

    /**
     * Test attribute "maritalStatus"
     */
    public function testPropertyMaritalStatus()
    {
    }

    /**
     * Test attribute "housingSituation"
     */
    public function testPropertyHousingSituation()
    {
    }

    /**
     * Test attribute "rentHouseDeductionPerMonth"
     */
    public function testPropertyRentHouseDeductionPerMonth()
    {
    }

    /**
     * Test attribute "residentSinceMonth"
     */
    public function testPropertyResidentSinceMonth()
    {
    }

    /**
     * Test attribute "residentSinceYear"
     */
    public function testPropertyResidentSinceYear()
    {
    }

    /**
     * Test attribute "employerName"
     */
    public function testPropertyEmployerName()
    {
    }

    /**
     * Test attribute "employerStreet"
     */
    public function testPropertyEmployerStreet()
    {
    }

    /**
     * Test attribute "employerHouseNum"
     */
    public function testPropertyEmployerHouseNum()
    {
    }

    /**
     * Test attribute "employerZip"
     */
    public function testPropertyEmployerZip()
    {
    }

    /**
     * Test attribute "employerCity"
     */
    public function testPropertyEmployerCity()
    {
    }

    /**
     * Test attribute "employerCountry"
     */
    public function testPropertyEmployerCountry()
    {
    }

    /**
     * Test attribute "employedSinceMonth"
     */
    public function testPropertyEmployedSinceMonth()
    {
    }

    /**
     * Test attribute "employedSinceYear"
     */
    public function testPropertyEmployedSinceYear()
    {
    }

    /**
     * Test attribute "newsletter"
     */
    public function testPropertyNewsletter()
    {
    }

    /**
     * Test attribute "rechtliches"
     */
    public function testPropertyRechtliches()
    {
    }

    /**
     * Test attribute "productIsFinance"
     */
    public function testPropertyProductIsFinance()
    {
    }

    /**
     * Test attribute "productIsIsnuranceAndPkv"
     */
    public function testPropertyProductIsIsnuranceAndPkv()
    {
    }

    /**
     * Test attribute "productIsPreventionAndHealth"
     */
    public function testPropertyProductIsPreventionAndHealth()
    {
    }

    /**
     * Test attribute "children"
     */
    public function testPropertyChildren()
    {
    }
}
