<?php
/**
 * KmcDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api mgmt.intaxx
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AndyDune\MgmtIntaxxApi;

/**
 * KmcDataTest Class Doc Comment
 *
 * @category    Class
 * @description KmcData
 * @package     AndyDune\MgmtIntaxxApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KmcDataTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "KmcData"
     */
    public function testKmcData()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "desiredAmount"
     */
    public function testPropertyDesiredAmount()
    {
    }

    /**
     * Test attribute "runningTime"
     */
    public function testPropertyRunningTime()
    {
    }

    /**
     * Test attribute "accountOwner"
     */
    public function testPropertyAccountOwner()
    {
    }

    /**
     * Test attribute "iban"
     */
    public function testPropertyIban()
    {
    }

    /**
     * Test attribute "bic"
     */
    public function testPropertyBic()
    {
    }

    /**
     * Test attribute "bank"
     */
    public function testPropertyBank()
    {
    }

    /**
     * Test attribute "maritalStatus"
     */
    public function testPropertyMaritalStatus()
    {
    }

    /**
     * Test attribute "amountOfChildren"
     */
    public function testPropertyAmountOfChildren()
    {
    }

    /**
     * Test attribute "propertyAvailable"
     */
    public function testPropertyPropertyAvailable()
    {
    }

    /**
     * Test attribute "houseSituation"
     */
    public function testPropertyHouseSituation()
    {
    }

    /**
     * Test attribute "houseDeductionPerMonth"
     */
    public function testPropertyHouseDeductionPerMonth()
    {
    }

    /**
     * Test attribute "residentSince"
     */
    public function testPropertyResidentSince()
    {
    }

    /**
     * Test attribute "employment"
     */
    public function testPropertyEmployment()
    {
    }

    /**
     * Test attribute "jobTitle"
     */
    public function testPropertyJobTitle()
    {
    }

    /**
     * Test attribute "sumIncome"
     */
    public function testPropertySumIncome()
    {
    }

    /**
     * Test attribute "employerTitle"
     */
    public function testPropertyEmployerTitle()
    {
    }

    /**
     * Test attribute "employerAddressZip"
     */
    public function testPropertyEmployerAddressZip()
    {
    }

    /**
     * Test attribute "employerAddressRegion"
     */
    public function testPropertyEmployerAddressRegion()
    {
    }

    /**
     * Test attribute "employerAddressCity"
     */
    public function testPropertyEmployerAddressCity()
    {
    }

    /**
     * Test attribute "employerAddressStreet"
     */
    public function testPropertyEmployerAddressStreet()
    {
    }

    /**
     * Test attribute "employerAddressHouse"
     */
    public function testPropertyEmployerAddressHouse()
    {
    }

    /**
     * Test attribute "employmentSinceMonth"
     */
    public function testPropertyEmploymentSinceMonth()
    {
    }

    /**
     * Test attribute "employmentSinceYear"
     */
    public function testPropertyEmploymentSinceYear()
    {
    }

    /**
     * Test attribute "isDataProcessingConfirmed"
     */
    public function testPropertyIsDataProcessingConfirmed()
    {
    }

    /**
     * Test attribute "isNewsletterConfirmed"
     */
    public function testPropertyIsNewsletterConfirmed()
    {
    }

    /**
     * Test attribute "placeOfBirth"
     */
    public function testPropertyPlaceOfBirth()
    {
    }

    /**
     * Test attribute "idNumber"
     */
    public function testPropertyIdNumber()
    {
    }

    /**
     * Test attribute "nationality"
     */
    public function testPropertyNationality()
    {
    }

    /**
     * Test attribute "isCardWasOrder"
     */
    public function testPropertyIsCardWasOrder()
    {
    }

    /**
     * Test attribute "cardWasOrderedDate"
     */
    public function testPropertyCardWasOrderedDate()
    {
    }

    /**
     * Test attribute "employerAddressCountry"
     */
    public function testPropertyEmployerAddressCountry()
    {
    }

    /**
     * Test attribute "isTermsAndConditionsConfirmed"
     */
    public function testPropertyIsTermsAndConditionsConfirmed()
    {
    }

    /**
     * Test attribute "isAgreedToUsePersonalDataConfirmed"
     */
    public function testPropertyIsAgreedToUsePersonalDataConfirmed()
    {
    }

    /**
     * Test attribute "loanRequest"
     */
    public function testPropertyLoanRequest()
    {
    }

    /**
     * Test attribute "isPowerOfAttorneyConfirmed"
     */
    public function testPropertyIsPowerOfAttorneyConfirmed()
    {
    }

    /**
     * Test attribute "occupationProfession"
     */
    public function testPropertyOccupationProfession()
    {
    }

    /**
     * Test attribute "occupation"
     */
    public function testPropertyOccupation()
    {
    }

    /**
     * Test attribute "cardPurpose"
     */
    public function testPropertyCardPurpose()
    {
    }

    /**
     * Test attribute "monthlyIncome"
     */
    public function testPropertyMonthlyIncome()
    {
    }
}
