<?php
/**
 * OrderMarksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api mgmt.intaxx
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.9.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AndyDune\MgmtIntaxxApi;

/**
 * OrderMarksTest Class Doc Comment
 *
 * @category    Class
 * @description Order marks or flags
 * @package     AndyDune\MgmtIntaxxApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderMarksTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderMarks"
     */
    public function testOrderMarks()
    {
    }

    /**
     * Test attribute "isEmailConfirmed"
     */
    public function testPropertyIsEmailConfirmed()
    {
    }

    /**
     * Test attribute "isSmsConfirmedByHash"
     */
    public function testPropertyIsSmsConfirmedByHash()
    {
    }

    /**
     * Test attribute "isSmsConfirmedByCode"
     */
    public function testPropertyIsSmsConfirmedByCode()
    {
    }

    /**
     * Test attribute "isOrderLikedToCollector"
     */
    public function testPropertyIsOrderLikedToCollector()
    {
    }

    /**
     * Test attribute "isOrderExported"
     */
    public function testPropertyIsOrderExported()
    {
    }

    /**
     * Test attribute "isSelfieLoaded"
     */
    public function testPropertyIsSelfieLoaded()
    {
    }

    /**
     * Test attribute "isSignatureLoaded"
     */
    public function testPropertyIsSignatureLoaded()
    {
    }

    /**
     * Test attribute "isIdCardFrontLoaded"
     */
    public function testPropertyIsIdCardFrontLoaded()
    {
    }

    /**
     * Test attribute "isIdCardBackLoaded"
     */
    public function testPropertyIsIdCardBackLoaded()
    {
    }
}
