<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api mgmt.intaxx
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.10.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AndyDune\MgmtIntaxxApi;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class
 * @description Order customar details.
 * @package     AndyDune\MgmtIntaxxApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "birthday"
     */
    public function testPropertyBirthday()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "countryCode"
     */
    public function testPropertyCountryCode()
    {
    }

    /**
     * Test attribute "countryName"
     */
    public function testPropertyCountryName()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "house"
     */
    public function testPropertyHouse()
    {
    }

    /**
     * Test attribute "room"
     */
    public function testPropertyRoom()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "zip"
     */
    public function testPropertyZip()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "userAgent"
     */
    public function testPropertyUserAgent()
    {
    }

    /**
     * Test attribute "domain"
     */
    public function testPropertyDomain()
    {
    }

    /**
     * Test attribute "cookie"
     */
    public function testPropertyCookie()
    {
    }

    /**
     * Test attribute "creditRequestInfo"
     */
    public function testPropertyCreditRequestInfo()
    {
    }

    /**
     * Test attribute "utmSource"
     */
    public function testPropertyUtmSource()
    {
    }

    /**
     * Test attribute "utmContent"
     */
    public function testPropertyUtmContent()
    {
    }

    /**
     * Test attribute "utmCampaign"
     */
    public function testPropertyUtmCampaign()
    {
    }

    /**
     * Test attribute "utmMedium"
     */
    public function testPropertyUtmMedium()
    {
    }

    /**
     * Test attribute "isInsurance"
     */
    public function testPropertyIsInsurance()
    {
    }

    /**
     * Test attribute "middleName"
     */
    public function testPropertyMiddleName()
    {
    }

    /**
     * Test attribute "anotherSurname"
     */
    public function testPropertyAnotherSurname()
    {
    }

    /**
     * Test attribute "anotherEmail"
     */
    public function testPropertyAnotherEmail()
    {
    }

    /**
     * Test attribute "landlinePhoneNumber"
     */
    public function testPropertyLandlinePhoneNumber()
    {
    }

    /**
     * Test attribute "isDataConfirmed"
     */
    public function testPropertyIsDataConfirmed()
    {
    }
}
