<?php
/**
 * OrderDataResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api mgmt.intaxx
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.9.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.19
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AndyDune\MgmtIntaxxApi;

/**
 * OrderDataResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Order full data
 * @package     AndyDune\MgmtIntaxxApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderDataResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderDataResponse"
     */
    public function testOrderDataResponse()
    {
    }

    /**
     * Test attribute "success"
     */
    public function testPropertySuccess()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "datetimeCreate"
     */
    public function testPropertyDatetimeCreate()
    {
    }

    /**
     * Test attribute "datetimeUpdate"
     */
    public function testPropertyDatetimeUpdate()
    {
    }

    /**
     * Test attribute "datetimeImport"
     */
    public function testPropertyDatetimeImport()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "kmc"
     */
    public function testPropertyKmc()
    {
    }

    /**
     * Test attribute "marks"
     */
    public function testPropertyMarks()
    {
    }
}
