<?php
/**
 * PaymentRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api mgmt.intaxx
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AndyDune\MgmtIntaxxApi;

/**
 * PaymentRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request for order payment
 * @package     AndyDune\MgmtIntaxxApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PaymentRequest"
     */
    public function testPaymentRequest()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "hash"
     */
    public function testPropertyHash()
    {
    }

    /**
     * Test attribute "force"
     */
    public function testPropertyForce()
    {
    }

    /**
     * Test attribute "urlRedirect"
     */
    public function testPropertyUrlRedirect()
    {
    }

    /**
     * Test attribute "update"
     */
    public function testPropertyUpdate()
    {
    }
}
