<?php
/**
 * PfsAccountInitialDataUserdefinedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api mgmt.intaxx
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AndyDune\MgmtIntaxxApi;

use PHPUnit\Framework\TestCase;

/**
 * PfsAccountInitialDataUserdefinedTest Class Doc Comment
 *
 * @category    Class
 * @description PfsAccountInitialDataUserdefined
 * @package     AndyDune\MgmtIntaxxApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PfsAccountInitialDataUserdefinedTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PfsAccountInitialDataUserdefined"
     */
    public function testPfsAccountInitialDataUserdefined()
    {
    }

    /**
     * Test attribute "occupation"
     */
    public function testPropertyOccupation()
    {
    }

    /**
     * Test attribute "occupationProfession"
     */
    public function testPropertyOccupationProfession()
    {
    }

    /**
     * Test attribute "cardPurpose"
     */
    public function testPropertyCardPurpose()
    {
    }

    /**
     * Test attribute "monthlyIncome"
     */
    public function testPropertyMonthlyIncome()
    {
    }
}
