<?php
/**
 * PfsAccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api mgmt.intaxx
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace AndyDune\MgmtIntaxxApi;

/**
 * PfsAccountTest Class Doc Comment
 *
 * @category    Class
 * @description PfsAccount
 * @package     AndyDune\MgmtIntaxxApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PfsAccountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PfsAccount"
     */
    public function testPfsAccount()
    {
    }

    /**
     * Test attribute "exist"
     */
    public function testPropertyExist()
    {
    }

    /**
     * Test attribute "issuingId"
     */
    public function testPropertyIssuingId()
    {
    }

    /**
     * Test attribute "cardholderId"
     */
    public function testPropertyCardholderId()
    {
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "cardStatus"
     */
    public function testPropertyCardStatus()
    {
    }

    /**
     * Test attribute "cardStatusId"
     */
    public function testPropertyCardStatusId()
    {
    }

    /**
     * Test attribute "initialData"
     */
    public function testPropertyInitialData()
    {
    }
}
