<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api mgmt.intaxx
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace AndyDune\MgmtIntaxxApi;

use AndyDune\MgmtIntaxxApi\Configuration;
use AndyDune\MgmtIntaxxApi\ApiException;
use AndyDune\MgmtIntaxxApi\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrderPost
     *
     * Create order with product of given brand.
     *
     */
    public function testCreateOrderPost()
    {
    }

    /**
     * Test case for customerPincodeCheckPost
     *
     * Request to check customer pincode..
     *
     */
    public function testCustomerPincodeCheckPost()
    {
    }

    /**
     * Test case for dataGet
     *
     * Check customer pincode..
     *
     */
    public function testDataGet()
    {
    }
}
