<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Api mgmt.intaxx
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.11.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace AndyDune\MgmtIntaxxApi;

use AndyDune\MgmtIntaxxApi\Configuration;
use AndyDune\MgmtIntaxxApi\ApiException;
use AndyDune\MgmtIntaxxApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  AndyDune\MgmtIntaxxApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for cardClientCompanyAssignPost
     *
     * Assign card client company to order.
     *
     */
    public function testCardClientCompanyAssignPost()
    {
    }

    /**
     * Test case for cardClientCompanyAvailableVariantsPost
     *
     * Get available variants of card client company.
     *
     */
    public function testCardClientCompanyAvailableVariantsPost()
    {
    }

    /**
     * Test case for createOrderPost
     *
     * Create order with product of given brand.
     *
     */
    public function testCreateOrderPost()
    {
    }

    /**
     * Test case for customerPincodeChangePost
     *
     * Request to change customer pincode..
     *
     */
    public function testCustomerPincodeChangePost()
    {
    }

    /**
     * Test case for customerPincodeCheckPost
     *
     * Request to check customer pincode..
     *
     */
    public function testCustomerPincodeCheckPost()
    {
    }

    /**
     * Test case for dataGet
     *
     * Basic data..
     *
     */
    public function testDataGet()
    {
    }

    /**
     * Test case for emailConfirmPost
     *
     * Customer email confirmation..
     *
     */
    public function testEmailConfirmPost()
    {
    }

    /**
     * Test case for getOrderDataPost
     *
     * Full order data.
     *
     */
    public function testGetOrderDataPost()
    {
    }

    /**
     * Test case for orderActionExecutePost
     *
     * Execute order action with code.
     *
     */
    public function testOrderActionExecutePost()
    {
    }

    /**
     * Test case for orderImagePost
     *
     * Get order image with code.
     *
     */
    public function testOrderImagePost()
    {
    }

    /**
     * Test case for orderSendSmsWithTemplatePost
     *
     * Send SMS for order with brand sms template.
     *
     */
    public function testOrderSendSmsWithTemplatePost()
    {
    }

    /**
     * Test case for paymentConditionsPost
     *
     * Check conditions for payment creation.
     *
     */
    public function testPaymentConditionsPost()
    {
    }

    /**
     * Test case for paymentCreatePost
     *
     * Create payment for order.
     *
     */
    public function testPaymentCreatePost()
    {
    }

    /**
     * Test case for paymentLastPaymentDataPost
     *
     * Get last payment data.
     *
     */
    public function testPaymentLastPaymentDataPost()
    {
    }

    /**
     * Test case for pfsAccountInfoPost
     *
     * Get accunt info.
     *
     */
    public function testPfsAccountInfoPost()
    {
    }

    /**
     * Test case for pfsWebhookPost
     *
     * Follow pfs webhook to this url.
     *
     */
    public function testPfsWebhookPost()
    {
    }

    /**
     * Test case for smsConfirmPost
     *
     * Customer sms confirmation..
     *
     */
    public function testSmsConfirmPost()
    {
    }

    /**
     * Test case for updateKmcDataImagesPost
     *
     * Upload KMC files.
     *
     */
    public function testUpdateKmcDataImagesPostForm()
    {
    }

    /**
     * Test case for updateKmcDataPost
     *
     * Upload KMC data.
     *
     */
    public function testUpdateKmcDataPost()
    {
    }

    /**
     * Test case for updateOrderPost
     *
     * Update customer data for order.
     *
     */
    public function testUpdateOrderPost()
    {
    }

    /**
     * Test case for uploadImagesPost
     *
     * Upload selfie, signature and maybe more.
     *
     */
    public function testUploadImagesPostForm()
    {
    }

    /**
     * Test case for uploadOrderFilePost
     *
     * Upload order file.
     *
     */
    public function testUploadOrderFilePostForm()
    {
    }

    /**
     * Test case for valueVariantsPost
     *
     * Get available value variants.
     *
     */
    public function testValueVariantsPost()
    {
    }
}
